apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
  namespace: sn-labs-danielbarraz
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
    - name: app-name
      type: string
    - name: build-image
      type: string
    - name: deploy-script
      type: string
      default: |
        oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
        kind: Task
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: output

    - name: flake8
      taskRef:
        name: flake8
        kind: Task
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: output

    - name: nose
      taskRef:
        name: nose
        kind: Task
      runAfter:
        - flake8
      params:
        - name: args
          value: "-v"
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - nose
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - buildah
      params:
        - name: SCRIPT
          value: $(params.deploy-script)